### ISSUE TITLE
作者搞反了Volley使用HttpStack

### ISSUE THREAD

**Issue by classops** [dodocat/AndroidNetworkDemo#2]
在 Android 3.0 以上 Volley 使用 ApacheHttpStack 作为传输协议, 在2.3 及以下使用 HttpURLConnection 作为传输层协议，是错误的。在 Android 3.0 以上 Volley 使用 HttpUrlConnection 作为传输协议, 在2.3 及以下使用 HttpClient的 作为传输层协议的。HttpClient很早就不建议使用了，所以Volley也只会在2.3以下用的，参考http://android-developers.blogspot.com/2011/09/androids-http-clients.html。当然更准确的来说自己可以修改的，我现在设置2.2使用HttpClient，2.3及以上使用HttpUrlConnection。不过一般现在开发都以4.0为最低API了。

**Comment by dodocat** [comment]
感谢 是这样的...

 我翻译这段的时候搞错了 你的回复很全面~
